### ISSUE TITLE
Error with expired credentials 

### ISSUE THREAD

**Issue by Keralin** [ivanfoo/joe#4]
Hi there!

Just found a error when you are using expired credentials tells you that is a problem from go and doesn't tell's you that's a problem with your credentials

```
keralin$ mortadelo assume --mfa -a live
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x81f3f0]

goroutine 1 [running]:
github.com/ivanfoo/mortadelo/commands.(*CmdAssume).setAWSCredentialsUsingMFA(0xc4200945a0, 0x0, 0x0)
    /home/keralin/go/src/github.com/ivanfoo/mortadelo/commands/assume.go:109 +0xd0
github.com/ivanfoo/mortadelo/commands.(*CmdAssume).Execute(0xc4200945a0, 0xc420096640, 0x0, 0x4, 0xc4200945a0, 0x1)
    /home/keralin/go/src/github.com/ivanfoo/mortadelo/commands/assume.go:42 +0x5c
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc42018e700, 0xc420094100, 0x4, 0x4, 0x412928, 0xc4200a95e0, 0xc420122200, 0xc420139f01, 0xc4201220c8)
    /home/keralin/go/src/github.com/jessevdk/go-flags/parser.go:333 +0x849
github.com/jessevdk/go-flags.(*Parser).Parse(0xc42018e700, 0x95329a, 0x9, 0x95b09a, 0x1a, 0x0)
    /home/keralin/go/src/github.com/jessevdk/go-flags/parser.go:190 +0x71
main.main()
    /home/keralin/go/src/github.com/ivanfoo/mortadelo/mortadelo.go:17 +0x2a3
```

Should be nice when this happens mortadelo promts you that your credentials are expired and you have to update it.

Greetings!

**Comment by ivanfoo** [comment]
This is fixed in v0.3.0 :)
